"use client";
import { useState } from 'react';
import { Upload, RefreshCw } from 'lucide-react';
import { DarkSelect } from '@/components/dark-select';
export function PoCommitmentUpload({ projects }: { projects: { id: string; project_name: string }[] }) {
  const [projectId, setProjectId] = useState(projects[0]?.id ?? ''); const [file, setFile] = useState<File | null>(null); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false);
  const submit = async () => { if (!file || !projectId) return setMessage('Select a project and ME2J Excel file.'); setLoading(true); setMessage(''); const form = new FormData(); form.set('project_id', projectId); form.set('file', file); const response = await fetch('/api/po-commitments/upload', { method: 'POST', body: form }); const body = await response.json(); setLoading(false); setMessage(response.ok ? `ME2J imported: ${body.imported} PO/WBS allocation rows.` : body.error || 'Upload failed.'); if (response.ok) setFile(null); };
  return <div className="rounded-2xl border border-line bg-panel p-5 shadow-card"><div className="flex items-center gap-2"><Upload className="h-4 w-4 text-accent" /><div><h3 className="text-sm font-bold text-text">ME2J PO Commitments</h3><p className="mt-0.5 text-xs text-muted">Upload ME2J with WBS Element. Deleted `L` lines are excluded in PO Spending.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-[1fr_1.4fr_auto]"><DarkSelect value={projectId} onChange={setProjectId} options={projects.map((p) => ({ value: p.id, label: p.project_name }))} /><input type="file" accept=".xlsx,.xls" onChange={(e) => setFile(e.target.files?.[0] ?? null)} className="rounded-lg border border-line bg-panel px-3 py-2 text-xs text-text file:mr-2 file:rounded file:border-0 file:bg-accent file:px-2 file:py-1 file:text-white"/><button type="button" onClick={() => void submit()} disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-lg bg-accent px-4 py-2 text-xs font-bold text-white disabled:opacity-50">{loading ? <RefreshCw className="h-3.5 w-3.5 animate-spin" /> : null}{loading ? 'Importing…' : 'Import ME2J'}</button></div>{message ? <p className="mt-3 text-xs font-semibold text-accent">{message}</p> : null}</div>;
}
