"use client";

import { useMemo, useState } from "react";
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { CalendarClock, CheckCircle2, Coins, Gauge, ShieldCheck, TrendingDown, TrendingUp, WalletCards } from "lucide-react";
import type { Gr55CostRow, HistoricalRevenueRow, PoCommitmentRow, ProjectCostElementControl, RevenueWBS } from "@/lib/types";
import { buildProjectForecast, REVENUE_FORECAST_BASIS_LABELS, type RevenueForecastBasis } from "@/lib/project-forecast";
import { formatCompactNumber, formatCurrency, formatPercent } from "@/lib/utils";

function Metric({ label, value, hint, icon: Icon, tone = "text-text" }: { label: string; value: string; hint: string; icon: any; tone?: string }) {
  return <div className="surface-card border border-line/70 bg-panel/90 p-4 shadow-card"><div className="flex items-center justify-between gap-2"><span className="section-kicker text-muted">{label}</span><Icon className="h-4 w-4 text-muted" /></div><div className={`data-value mt-3 text-[1.12rem] font-semibold ${tone}`}>{value}</div><p className="mt-2 text-xs text-muted/75">{hint}</p></div>;
}

function shortPeriod(period: string | null) {
  if (!period) return "Not available";
  const [year, month] = period.split("-");
  return new Date(Date.UTC(Number(year), Number(month) - 1, 1)).toLocaleDateString("en-US", { month: "short", year: "2-digit", timeZone: "UTC" });
}

function CumulativeForecastChart({ title, subtitle, data, actualKey, forecastKey, plannedKey, actualLabel, forecastLabel, plannedLabel, color, finalValue }: {
  title: string;
  subtitle: string;
  data: ReturnType<typeof buildProjectForecast>["cumulativeTimeline"];
  actualKey: "actualRevenue" | "actualCost";
  forecastKey: "forecastRevenue" | "forecastCost";
  plannedKey: "plannedRevenue" | "plannedCost";
  actualLabel: string;
  forecastLabel: string;
  plannedLabel: string;
  color: string;
  finalValue: number;
}) {
  return <div className="surface-card min-w-0 border border-line/60 bg-panel/90 p-4 shadow-card sm:p-5">
    <div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
      <div><h3 className="text-sm font-bold text-text">{title}</h3><p className="mt-1 text-xs text-muted">{subtitle}</p></div>
      <div className="rounded-lg bg-panel2 px-2.5 py-1.5 text-left sm:text-right"><div className="text-[9px] font-bold uppercase tracking-wider text-muted">At completion</div><div className="mt-0.5 font-mono text-xs font-bold text-text">{formatCurrency(finalValue)}</div></div>
    </div>
    <div className="mt-4 h-72 overflow-x-auto"><div className="h-full min-w-[660px]" style={{ width: Math.max(660, data.length * 76) }}><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{ top: 12, right: 16, left: 4, bottom: 4 }}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="rgb(var(--color-line) / 0.35)" /><XAxis dataKey="period" fontSize={10} tickLine={false} axisLine={false} /><YAxis tickFormatter={(value) => formatCompactNumber(value)} fontSize={10} tickLine={false} axisLine={false} width={56} /><Tooltip formatter={(value: number, name: string) => [formatCurrency(value), name]} labelFormatter={(value) => `Month: ${value}`} /><Legend verticalAlign="top" height={28} iconType="circle" iconSize={7} wrapperStyle={{ fontSize: 10 }} /><ReferenceLine x={data.find((point) => point.isCurrentMonth)?.period} stroke="#94a3b8" strokeDasharray="4 4" label={{ value: "Today", position: "top", fontSize: 10, fill: "#64748b" }} /><Line type="monotone" dataKey={actualKey} name={actualLabel} stroke={color} strokeWidth={2.5} dot={{ r: 2 }} connectNulls={false} /><Line type="monotone" dataKey={forecastKey} name={forecastLabel} stroke={color} strokeWidth={2.5} strokeDasharray="7 5" dot={{ r: 2 }} connectNulls={false} /><Line type="monotone" dataKey={plannedKey} name={plannedLabel} stroke="#64748b" strokeWidth={1.5} strokeDasharray="3 5" dot={false} /></LineChart></ResponsiveContainer></div></div>
    <div className="mt-2 flex items-center gap-2 text-[10px] text-muted"><span className="inline-block h-2 w-2 rounded-full" style={{ backgroundColor: color }} /><span>Solid = actual</span><span className="ml-2 inline-block h-px w-4 border-t-2 border-dashed" style={{ borderColor: color }} /><span>Dashed = forecast</span></div>
  </div>;
}

export function ProjectForecastPanel({ costRows, revenueRows, gr55Rows, historicalRevenueRows, poCommitments, costElementControl, revenueTrend, recognizedRevenueToDate }: { costRows: RevenueWBS[]; revenueRows: RevenueWBS[]; gr55Rows: Gr55CostRow[]; historicalRevenueRows: HistoricalRevenueRow[]; poCommitments: PoCommitmentRow[]; costElementControl: ProjectCostElementControl[]; revenueTrend: Array<{ period: string; recognizedRevenue: number }>; recognizedRevenueToDate: number }) {
  const [selectedBasis, setSelectedBasis] = useState<RevenueForecastBasis>("last3");
  const [selectedPeriod, setSelectedPeriod] = useState<string | null>(null);
  const [targetCompletionDate, setTargetCompletionDate] = useState(() => { const date = new Date(); date.setMonth(date.getMonth() + 6, 0); return date.toISOString().slice(0, 10); });
  const [monthlyRevenueTarget, setMonthlyRevenueTarget] = useState("");
  const forecast = useMemo(() => buildProjectForecast({ costRows, revenueRows, gr55Rows, historicalRevenueRows, poCommitments, costElementControl, revenueTrend, recognizedRevenueToDate, selectedBasis, targetCompletionDate, monthlyRevenueTarget: Number(monthlyRevenueTarget) || 0 }), [costRows, revenueRows, gr55Rows, historicalRevenueRows, poCommitments, costElementControl, revenueTrend, recognizedRevenueToDate, selectedBasis, targetCompletionDate, monthlyRevenueTarget]);
  const selected = forecast.timeline.find((point) => point.period === selectedPeriod);
  const ratioText = forecast.cost.costPerRevenue === null ? "Not available" : `${forecast.cost.costPerRevenue.toFixed(2)} SAR`;
  const trendIcon = forecast.revenueTrend === "Increasing" ? TrendingUp : forecast.revenueTrend === "Decreasing" ? TrendingDown : Gauge;
  const stabilityTone = forecast.revenueStability === "High Variation" ? "text-danger" : forecast.revenueStability === "Medium Stability" ? "text-warning" : "text-success";
  const confidenceTone = forecast.forecastConfidence === "High Confidence" ? "text-success" : forecast.forecastConfidence === "Medium Confidence" ? "text-warning" : "text-danger";
  const activeHistoricalBasis = selectedBasis === "recommended" ? forecast.recommendedBasis : selectedBasis;
  const selectedTargetRow = selectedBasis === "targetDate" || selectedBasis === "monthlyTarget" ? {
    label: selectedBasis === "targetDate" ? `Target Completion Date (${targetCompletionDate})` : "Monthly Revenue Target",
    monthlyRunRate: forecast.revenue.selectedRunRate,
    completionPeriod: forecast.completionPeriod,
  } : null;

  return <div className="space-y-5 print-container">
    <div className="surface-card border border-line/60 bg-panel/90 p-4 shadow-card sm:p-5">
      <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
        <div><h2 className="flex items-center gap-2 text-base font-bold text-text"><TrendingUp className="h-5 w-5 text-accent" />Revenue &amp; Cost Forecast</h2><p className="mt-1 text-xs text-muted">Select a historical revenue run rate. It also determines the cost-to-revenue ratio.</p></div>
        <div className="flex items-center gap-3 rounded-lg border border-line/60 bg-panel2 px-3 py-2"><div><div className="text-[9px] font-bold uppercase tracking-wider text-muted">Completion</div><div className="font-mono text-sm font-bold text-text">{shortPeriod(forecast.completionPeriod)}</div></div><span className="h-7 w-px bg-line/60" /><div className="text-[10px] font-semibold text-success">{forecast.includedCostElementCount} approved<br />cost elements</div></div>
      </div>
      <div className="mt-3 flex flex-col gap-3 border-t border-line/60 pt-3 xl:flex-row xl:items-center">
        <div className="min-w-0 flex-1"><div className="mb-1.5 text-[10px] font-bold uppercase tracking-wider text-muted">Historical performance</div><div className="grid grid-cols-2 gap-1 sm:grid-cols-3 xl:grid-cols-5">{(["last1", "last2", "last3", "ytd", "recommended"] as RevenueForecastBasis[]).map((basis) => <button key={basis} type="button" aria-pressed={selectedBasis === basis} onClick={() => setSelectedBasis(basis)} className={`min-h-9 rounded-lg border px-2 py-1.5 text-xs font-bold leading-tight transition ${selectedBasis === basis ? "border-accent bg-accent text-white" : "border-line bg-panel2 text-muted hover:border-accent/50 hover:text-text"}`}>{basis === "recommended" ? "Smart forecast" : REVENUE_FORECAST_BASIS_LABELS[basis]}</button>)}</div></div>
        <div className="min-w-0 xl:w-[270px]"><div className="mb-1.5 text-[10px] font-bold uppercase tracking-wider text-muted">Target setting</div><div className="grid grid-cols-2 gap-1">{(["targetDate", "monthlyTarget"] as RevenueForecastBasis[]).map((basis) => <button key={basis} type="button" aria-pressed={selectedBasis === basis} onClick={() => setSelectedBasis(basis)} className={`min-h-9 rounded-lg border px-2 py-1.5 text-xs font-bold leading-tight transition ${selectedBasis === basis ? "border-accent bg-accent text-white" : "border-line bg-panel2 text-muted hover:border-accent/50 hover:text-text"}`}>{basis === "targetDate" ? "Completion date" : "Monthly target"}</button>)}</div></div>
        <div className="flex min-w-0 items-center gap-2 rounded-lg border border-success/25 bg-success/5 px-3 py-2 xl:w-[360px]"><CheckCircle2 className="h-4 w-4 shrink-0 text-success" /><p className="min-w-0 flex-1 truncate text-xs text-muted"><span className="font-bold text-success">Recommended: {REVENUE_FORECAST_BASIS_LABELS[forecast.recommendedBasis]}.</span> {forecast.recommendationReason}</p>{selectedBasis !== "recommended" ? <button type="button" className="shrink-0 rounded-md bg-success px-2 py-1 text-[10px] font-bold text-white" onClick={() => setSelectedBasis("recommended")}>Apply</button> : null}</div>
      </div>
      {selectedBasis === "targetDate" ? <div className="mt-3 flex flex-col gap-2 rounded-lg border border-accent/30 bg-accent/5 p-3 sm:flex-row sm:items-center"><label className="flex items-center gap-2 text-xs font-bold text-text">Target completion date<input type="date" value={targetCompletionDate} onChange={(event) => setTargetCompletionDate(event.target.value)} className="rounded-lg border border-line bg-panel px-2 py-1.5 font-normal text-text outline-none focus:border-accent" /></label><p className="text-[11px] text-muted">Required revenue is calculated backwards from this date.</p></div> : null}
      {selectedBasis === "monthlyTarget" ? <div className="mt-3 flex flex-col gap-2 rounded-lg border border-accent/30 bg-accent/5 p-3 sm:flex-row sm:items-center"><label className="flex items-center gap-2 text-xs font-bold text-text">Monthly target (SAR)<input type="number" min="0" step="1000" value={monthlyRevenueTarget} onChange={(event) => setMonthlyRevenueTarget(event.target.value)} placeholder="Enter amount" className="w-full rounded-lg border border-line bg-panel px-2 py-1.5 font-normal text-text outline-none focus:border-accent sm:w-48" /></label><p className="text-[11px] text-muted">Future months use this management target.</p></div> : null}
    </div>

    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      <Metric label="Selected monthly run rate" value={formatCurrency(forecast.revenue.selectedRunRate)} hint={REVENUE_FORECAST_BASIS_LABELS[selectedBasis]} icon={TrendingUp} tone="text-success" />
      <Metric label="Current recognized revenue" value={formatCurrency(forecast.revenue.currentActual)} hint={`Management POC in ${forecast.currentPeriod}`} icon={Coins} />
      <Metric label="Current month revised forecast" value={formatCurrency(forecast.revenue.currentForecast)} hint="Recognized revenue plus remaining-day forecast" icon={Gauge} tone="text-success" />
      <Metric label="Remaining project revenue" value={formatCurrency(forecast.revenue.remaining)} hint="Planned revenue less recognized revenue" icon={WalletCards} />
      <Metric label="Revenue trend" value={forecast.revenueTrend} hint="Based on the latest 3 completed months" icon={trendIcon} tone={forecast.revenueTrend === "Decreasing" ? "text-danger" : forecast.revenueTrend === "Increasing" ? "text-success" : "text-accent"} />
      <Metric label="Revenue stability" value={forecast.revenueStability} hint={forecast.revenueStability === "High Variation" ? "Monthly revenue varies heavily" : "Monthly revenue variation"} icon={Gauge} tone={stabilityTone} />
      <Metric label="Forecast confidence" value={forecast.forecastConfidence} hint="History coverage and monthly variation" icon={ShieldCheck} tone={confidenceTone} />
      <Metric label="Forecast cost at completion" value={formatCurrency(forecast.eac)} hint={`Cost per SAR 1 revenue: ${ratioText}`} icon={WalletCards} tone={forecast.expectedOverrun > 0 ? "text-danger" : "text-text"} />
    </div>

    <section className="space-y-3">
      <div className="flex flex-col gap-1 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-base font-bold text-text">Cumulative forecast outlook</h2><p className="text-xs text-muted">Updates immediately when the forecast method changes. The dashed line begins from the latest actual cumulative balance.</p></div><span className="text-xs font-bold text-accent">Basis: {REVENUE_FORECAST_BASIS_LABELS[selectedBasis]}</span></div>
      <div className="grid gap-5 xl:grid-cols-2">
        <CumulativeForecastChart title="Cumulative Revenue Forecast" subtitle="Recognized revenue to date and projected contract-revenue completion." data={forecast.cumulativeTimeline} actualKey="actualRevenue" forecastKey="forecastRevenue" plannedKey="plannedRevenue" actualLabel="Actual cumulative revenue" forecastLabel="Forecast cumulative revenue" plannedLabel="Planned / contract revenue" color="#10b981" finalValue={forecast.revenue.planned} />
        <CumulativeForecastChart title="Cumulative Cost Forecast" subtitle="Eligible actual cost and estimated cost at completion using the selected cost-to-revenue ratio." data={forecast.cumulativeTimeline} actualKey="actualCost" forecastKey="forecastCost" plannedKey="plannedCost" actualLabel="Actual cumulative cost" forecastLabel="Forecast cumulative cost" plannedLabel="Planned cost" color="#8b5cf6" finalValue={forecast.eac} />
      </div>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
        <Metric label="Projected completion" value={shortPeriod(forecast.completionPeriod)} hint="At the selected revenue run rate" icon={CalendarClock} />
        <Metric label="Forecast revenue at completion" value={formatCurrency(forecast.revenue.planned)} hint="Capped at planned / contract revenue" icon={TrendingUp} tone="text-success" />
        <Metric label="Estimated cost at completion" value={formatCurrency(forecast.eac)} hint="Actual cost plus forecast future cost" icon={WalletCards} tone={forecast.expectedOverrun > 0 ? "text-danger" : "text-text"} />
        <Metric label="Forecast margin" value={forecast.expectedGMPercent === null ? "Not available" : formatPercent(forecast.expectedGMPercent)} hint={formatCurrency(forecast.expectedFinalGM)} icon={Gauge} tone={forecast.expectedFinalGM < 0 ? "text-danger" : "text-success"} />
        <Metric label="Forecast vs planned cost" value={`${forecast.eac - forecast.plannedCost >= 0 ? "+" : "-"}${formatCurrency(Math.abs(forecast.eac - forecast.plannedCost))}`} hint={forecast.eac > forecast.plannedCost ? "Above planned cost" : "Within planned cost"} icon={ShieldCheck} tone={forecast.eac > forecast.plannedCost ? "text-danger" : "text-success"} />
      </div>
    </section>

    {selectedBasis === "targetDate" || selectedBasis === "monthlyTarget" ? <div className="surface-card border border-line/60 bg-panel/90 p-5 shadow-card"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-sm font-bold text-text">Target run-rate analysis</h3><p className="mt-1 text-xs text-muted">Required performance compared with the current 3-month actual revenue run rate.</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${forecast.targetStatusTone === "success" ? "bg-success/10 text-success" : forecast.targetStatusTone === "warning" ? "bg-warning/10 text-warning" : "bg-danger/10 text-danger"}`}>{forecast.targetStatus}</span></div><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><Metric label={selectedBasis === "targetDate" ? "Target completion date" : "Monthly revenue target"} value={selectedBasis === "targetDate" ? targetCompletionDate : formatCurrency(forecast.monthlyRevenueTarget ?? 0)} hint={selectedBasis === "targetDate" ? "Required finish date" : "Manual target for future months"} icon={CalendarClock} /><Metric label="Required monthly revenue" value={formatCurrency(forecast.revenue.selectedRunRate)} hint="Selected target-based run rate" icon={TrendingUp} tone="text-accent" /><Metric label="Current 3-month run rate" value={formatCurrency(forecast.methodComparison.find((method) => method.basis === "last3")?.monthlyRunRate ?? 0)} hint="Actual completed-month performance" icon={TrendingUp} /><Metric label="Run-rate gap" value={`${forecast.runRateGap >= 0 ? "+" : ""}${formatCurrency(forecast.runRateGap)}`} hint="Selected run rate less 3-month average" icon={Gauge} tone={forecast.runRateGap > 0 ? "text-danger" : "text-success"} /><Metric label="Required improvement" value={forecast.runRateGapPercent === null ? "Not available" : `${forecast.runRateGapPercent >= 0 ? "+" : ""}${forecast.runRateGapPercent.toFixed(1)}%`} hint="Versus current 3-month average" icon={Gauge} tone={forecast.runRateGapPercent !== null && forecast.runRateGapPercent > 15 ? "text-danger" : "text-success"} /><Metric label="Expected final GM %" value={forecast.expectedGMPercent === null ? "Not available" : formatPercent(forecast.expectedGMPercent)} hint={`Expected GM: ${formatCurrency(forecast.expectedFinalGM)}`} icon={WalletCards} tone={forecast.expectedFinalGM < 0 ? "text-danger" : "text-success"} /></div>{forecast.runRateGapPercent !== null && forecast.runRateGapPercent > 15 ? <p className="mt-4 rounded-lg border border-warning/40 bg-warning/5 px-3 py-2 text-xs text-warning">To achieve this target, monthly revenue needs to increase approximately {forecast.runRateGapPercent.toFixed(1)}% compared with the current 3-month average.</p> : null}</div> : null}

    <div className="grid gap-5 xl:grid-cols-2">
      <div className="surface-card border border-line/60 bg-panel/90 p-5 shadow-card"><div className="flex items-center justify-between gap-3"><div><h3 className="text-sm font-bold text-text">Forecast basis comparison</h3><p className="mt-1 text-xs text-muted">The active selection is highlighted, alongside each historical-performance method.</p></div><CalendarClock className="h-5 w-5 text-accent" /></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[560px] text-left text-xs"><thead className="border-b border-line text-[10px] uppercase tracking-wider text-muted"><tr><th className="pb-3 font-bold">Forecast method</th><th className="pb-3 text-right font-bold">Monthly run rate</th><th className="pb-3 text-right font-bold">Expected completion</th></tr></thead><tbody>{selectedTargetRow ? <tr className="border-b border-accent/30 bg-accent/10"><td className="py-3 font-bold text-accent">{selectedTargetRow.label}<span className="ml-2 rounded bg-accent px-1.5 py-0.5 text-[9px] font-bold text-white">SELECTED</span></td><td className="py-3 text-right font-mono font-bold text-accent">{formatCurrency(selectedTargetRow.monthlyRunRate)}</td><td className="py-3 text-right font-bold text-accent">{shortPeriod(selectedTargetRow.completionPeriod)}</td></tr> : null}{forecast.methodComparison.map((method) => <tr key={method.basis} className={`border-b border-line/50 ${method.basis === activeHistoricalBasis ? "bg-accent/5" : ""}`}><td className="py-3 font-semibold text-text">{method.label}{method.basis === activeHistoricalBasis ? <span className="ml-2 rounded bg-accent/10 px-1.5 py-0.5 text-[9px] font-bold text-accent">SELECTED</span> : null}{method.basis === forecast.recommendedBasis ? <span className="ml-2 rounded bg-success/10 px-1.5 py-0.5 text-[9px] font-bold text-success">RECOMMENDED</span> : null}</td><td className="py-3 text-right font-mono text-text">{method.available ? formatCurrency(method.monthlyRunRate) : "No history"}</td><td className="py-3 text-right font-medium text-text">{shortPeriod(method.completionPeriod)}</td></tr>)}</tbody></table></div></div>
      <div className="surface-card border border-line/60 bg-panel/90 p-5 shadow-card"><h3 className="text-sm font-bold text-text">Scenario comparison</h3><p className="mt-1 text-xs text-muted">Expected uses {REVENUE_FORECAST_BASIS_LABELS[selectedBasis]}; conservative and optimistic use the lowest and highest historical run rates.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[610px] text-left text-xs"><thead className="border-b border-line text-[10px] uppercase tracking-wider text-muted"><tr><th className="pb-3 font-bold">Scenario</th><th className="pb-3 text-right font-bold">Revenue / month</th><th className="pb-3 text-right font-bold">Completion</th><th className="pb-3 text-right font-bold">Forecast final cost</th></tr></thead><tbody>{forecast.scenarios.map((scenario) => <tr key={scenario.name} className={`border-b border-line/50 ${scenario.name === "Expected" ? "bg-accent/5" : ""}`}><td className="py-3 font-semibold text-text">{scenario.name}{scenario.name === "Expected" ? <span className="ml-2 rounded bg-accent/10 px-1.5 py-0.5 text-[9px] font-bold text-accent">SELECTED</span> : null}</td><td className="py-3 text-right font-mono text-text">{formatCurrency(scenario.monthlyRunRate)}</td><td className="py-3 text-right font-medium text-text">{shortPeriod(scenario.completionPeriod)}</td><td className="py-3 text-right font-mono text-text">{formatCurrency(scenario.forecastFinalCost)}</td></tr>)}</tbody></table></div><p className="mt-3 text-[11px] text-muted">If final cost is unchanged across scenarios, this is expected: all scenarios recognise the same remaining contract revenue using the same selected cost-to-revenue ratio. The completion timing and monthly cash-flow profile still change.</p></div>
    </div>

    <div className="surface-card border border-line/60 bg-panel/90 p-5 shadow-card"><div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="text-sm font-bold text-text">Revenue and cost completion timeline</h3><p className="mt-1 text-[11px] text-muted">Click a column to view its revenue and cost calculation. Current-month recognition is never reduced.</p></div><span className="text-[10px] font-medium text-accent">Current month: {forecast.currentPeriod}</span></div><div className="mt-4 h-80 overflow-x-auto"><div className="h-full min-w-[760px]" style={{ width: Math.max(760, forecast.timeline.length * 96) }}><ResponsiveContainer width="100%" height="100%"><BarChart data={forecast.timeline} margin={{ top: 15, right: 20, left: 4, bottom: 0 }} onClick={(event: any) => { const point = event?.activePayload?.[0]?.payload; if (point) setSelectedPeriod(point.period); }}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="rgb(var(--color-line) / 0.3)" /><XAxis dataKey="period" fontSize={10} tickLine={false} /><YAxis tickFormatter={(value) => formatCompactNumber(value)} fontSize={10} tickLine={false} /><Tooltip formatter={(value: number, name: string) => [formatCurrency(value), name]} /><Legend verticalAlign="top" height={28} iconType="circle" iconSize={7} wrapperStyle={{ fontSize: 10 }} /><Bar dataKey="revenueActual" name="Current recognized revenue (POC)" fill="#2563eb" radius={[3, 3, 0, 0]} /><Bar dataKey="revenueForecast" name="Revenue forecast" fill="#10b981" radius={[3, 3, 0, 0]} /><Bar dataKey="costActual" name="Eligible actual cost" fill="#f59e0b" radius={[3, 3, 0, 0]} /><Bar dataKey="costForecast" name="Cost forecast" fill="#8b5cf6" radius={[3, 3, 0, 0]} /></BarChart></ResponsiveContainer></div></div>
      {selected ? <div className="mt-4 rounded-xl border border-accent/30 bg-accent/5 p-4"><div className="text-[10px] font-bold uppercase tracking-wider text-accent">Forecast detail - {selected.period}{selected.isCurrentMonth ? " - Current month" : ""}</div><div className="mt-3 grid gap-3 text-xs text-muted sm:grid-cols-2 lg:grid-cols-4"><div><strong className="block text-text">Recognized revenue (POC)</strong>{formatCurrency(selected.revenueActual ?? 0)}</div><div><strong className="block text-text">Revenue forecast</strong>{formatCurrency(selected.revenueForecast ?? 0)}</div><div><strong className="block text-text">Eligible cost actual</strong>{formatCurrency(selected.costActual ?? 0)}</div><div><strong className="block text-text">Cost forecast</strong>{formatCurrency(selected.costForecast ?? 0)}</div></div><p className="mt-3 text-xs text-muted">{selected.isCurrentMonth ? "Current month equals management POC recognized revenue to date plus the selected run rate for remaining days." : "Future revenue uses the selected run rate; future cost uses the eligible cost-to-revenue ratio from the same selected months."}{selected.isFinalPeriod ? " This is the final capped period, so forecast revenue does not exceed remaining contract revenue." : ""}</p></div> : null}
    </div>

    <div className="grid gap-5 xl:grid-cols-2"><div className="surface-card border border-line/60 bg-panel/90 p-5 shadow-card"><h3 className="text-sm font-bold text-text">Revenue forecast logic</h3><div className="mt-3 space-y-2 text-xs text-muted"><p><strong className="text-text">Selected basis:</strong> {REVENUE_FORECAST_BASIS_LABELS[selectedBasis]} using {forecast.completedPeriods.join(", ") || "no completed months"}.</p><p><strong className="text-text">Current month:</strong> management POC recognized revenue plus the selected daily run rate for remaining days.</p><p><strong className="text-text">Future:</strong> the selected monthly run rate until remaining contract revenue is zero.</p></div></div><div className="surface-card border border-line/60 bg-panel/90 p-5 shadow-card"><h3 className="text-sm font-bold text-text">Cost forecast logic</h3><div className="mt-3 space-y-2 text-xs text-muted"><p><strong className="text-text">Cost ratio:</strong> {formatCurrency(forecast.cost.eligibleActualForBasis)} eligible cost divided by {formatCurrency(forecast.revenue.selectedRunRate * forecast.completedPeriods.length)} revenue from the selected basis.</p><p><strong className="text-text">Current month cost:</strong> {formatCurrency(forecast.cost.currentActual)} posted plus cost required for remaining forecast revenue.</p><p><strong className="text-text">Monthly forecast cost:</strong> {formatCurrency(forecast.cost.futureMonthlyForecast)} while the timeline remains active.</p></div></div></div>
  </div>;
}
