import { NextResponse } from 'next/server';
import * as XLSX from 'xlsx';
import { requireAdminUser } from '@/lib/current-user';
import { createSupabaseAdminClient } from '@/lib/supabase/admin';
export const runtime = 'nodejs';
type VendorRow = { vendor_id: string; vendor_name: string; city: string | null; postal_code: string | null; source_status: string | null };
export async function GET() { try { await requireAdminUser(); const supabase = await createSupabaseAdminClient(); const { count, error } = await supabase.from('vendor_master').select('*', { count: 'exact', head: true }); if (error) throw error; const { data: latest, error: latestError } = await supabase.from('vendor_master').select('source_file_name, imported_at, imported_by').order('imported_at', { ascending: false }).limit(1).maybeSingle(); if (latestError) throw latestError; return NextResponse.json({ total: count ?? 0, uploadedAt: latest?.imported_at ?? null, uploadedBy: latest?.imported_by ?? null, fileName: latest?.source_file_name ?? null }); } catch (cause) { return responseForError(cause); } }
export async function POST(request: Request) { try { const user = await requireAdminUser(); const form = await request.formData(); const file = form.get('file'); if (!(file instanceof File)) return NextResponse.json({ error: 'Choose a Vendor Master Excel file first.' }, { status: 400 }); if (!/\.(xlsx|xls)$/i.test(file.name)) return NextResponse.json({ error: 'Only Excel files (.xlsx or .xls) are supported.' }, { status: 400 }); const workbook = XLSX.read(await file.arrayBuffer(), { type: 'array' }); const sheet = workbook.Sheets[workbook.SheetNames[0]]; const raw = XLSX.utils.sheet_to_json<Record<string, unknown>>(sheet, { defval: '', raw: false }); const rows = raw.map(toVendorRow).filter((row): row is VendorRow => Boolean(row)); if (!rows.length) return NextResponse.json({ error: 'No valid vendor records found. Required columns are Vendor ID and Vendor/Supplier/Sub Con Name.' }, { status: 400 }); if (rows.length !== raw.length) return NextResponse.json({ error: 'Every row must include Vendor ID and Vendor/Supplier/Sub Con Name.' }, { status: 400 }); const unique = new Map(rows.map((row) => [row.vendor_id, row])); if (unique.size !== rows.length) return NextResponse.json({ error: 'The file contains duplicate Vendor IDs. Correct them before uploading.' }, { status: 400 }); const supabase = await createSupabaseAdminClient(); const { error: deleteError } = await supabase.from('vendor_master').delete().neq('vendor_id', ''); if (deleteError) throw deleteError; const stamp = new Date().toISOString(); const dbRows = [...unique.values()].map((row) => ({ ...row, source_file_name: file.name, imported_at: stamp, imported_by: user.id })); for (let index = 0; index < dbRows.length; index += 500) { const { error } = await supabase.from('vendor_master').insert(dbRows.slice(index, index + 500)); if (error) throw error; } return NextResponse.json({ total: dbRows.length, imported: dbRows.length, uploadedAt: stamp, uploadedBy: user.email, fileName: file.name }); } catch (cause) { return responseForError(cause); } }
function toVendorRow(row: Record<string, unknown>): VendorRow | null { const value = (key: string) => String(row[key] ?? '').trim(); const vendor_id = value('Vendor ID'); const vendor_name = value('Vendor/Supplier/Sub Con Name'); if (!vendor_id || !vendor_name) return null; return { vendor_id, vendor_name, city: value('City') || null, postal_code: value('PostalCode') || null, source_status: value('DelF') || null }; }
function responseForError(cause: unknown) { const message = cause instanceof Error ? cause.message : 'Vendor Master request failed.'; return NextResponse.json({ error: message }, { status: message.includes('Admin access') ? 403 : 500 }); }
